### ISSUE TITLE
Generate graphics

### ISSUE THREAD

**Issue by fervi** [kwadroke/free-hl-data#1]
Sorry, this issue isn't for free-hl-data :(

I jest need to create sprites like you in project

So get sprites original name, resolution and create
https://github.com/kwadroke/free-hl-data/blob/master/valve/halflife.wad/%2B0button1.png

So for example - orange background and file name on that.

And sorry again for spam, but I really need it for my game

**Comment by kwadroke** [comment]
I have a Linux Bash script that uses ImageMagick that I planned on uploading to this repository. I'll see if I can get it committed soon.

**Comment by fervi** [comment]
Ok, great! :-)

**Comment by kwadroke** [comment]
Haven't forgotten about this, just haven't had time to commit it yet due to Christmas.

**Comment by fervi** [comment]
Ok, I've got this script from someone else (not exacly, but works) ;)
